package Shared;

//import java.io.Serializable;

import Server.TopicSelection;

public enum Request  {
    MESSAGE, AUTHFAILED, AUTHSUCCES, LOGIN, PASS, TOPICSELECTION, JOINTOPIC, CREATETOPIC, TOPICCREATIONSUCCES, TOPICCREATIONFAIL,  TOPICJOINSUCCES, EXIT, ACCOUNTCREATION, ACCOUNTLOGIN,
    ACCOUNTCREATIONSUCCES, ACCOUNTCREATIONFAIL, BACKMENU
}
